"""
Sentinel ChatML Template & Dialogue Formatting
=============================================
Provides standard multi-turn ChatML prompt structuring and reasoning parser.
"""

from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

IM_START = "<|im_start|>"
IM_END = "<|im_end|>"
THINK_START = "<think>"
THINK_END = "</think>"

DEFAULT_SYSTEM_PROMPT = (
    "You are Sentinel, an autonomous sovereign neural language model. "
    "Think through problems systematically step-by-step inside <think>...</think> tags, "
    "then provide a clear, accurate, and concise response."
)


def format_chat_prompt(
    messages: List[Dict[str, str]],
    system_prompt: str = DEFAULT_SYSTEM_PROMPT,
    add_generation_prompt: bool = True
) -> str:
    """
    Formats a list of role/content dictionaries into standard ChatML text.
    
    Format:
    <|im_start|>system
    {system_prompt}<|im_end|>
    <|im_start|>user
    {user_message}<|im_end|>
    <|im_start|>assistant
    <think>
    """
    lines: List[str] = []

    # Always ensure system prompt is present at the beginning
    has_system = any(m.get("role") == "system" for m in messages)
    if not has_system:
        lines.append(f"{IM_START}system\n{system_prompt}{IM_END}")

    for msg in messages:
        role = msg["role"]
        content = msg["content"].strip()
        lines.append(f"{IM_START}{role}\n{content}{IM_END}")

    prompt = "\n".join(lines)
    if add_generation_prompt:
        prompt += f"\n{IM_START}assistant\n{THINK_START}\n"

    return prompt


def parse_reasoning_and_response(raw_output: str) -> Tuple[Optional[str], str]:
    """
    Separates the <think> ... </think> reasoning block from the final answer.
    Handles cases where <think> was part of the prompt or generated by the model.
    """
    cleaned = raw_output.replace(IM_END, "").replace(IM_START, "").strip()

    # Case 1: Both <think> and </think> exist in output
    if "<think>" in cleaned and "</think>" in cleaned:
        think_match = re.search(r"<think>(.*?)</think>", cleaned, flags=re.DOTALL)
        if think_match:
            reasoning = think_match.group(1).strip()
            response = cleaned[think_match.end():].strip()
            return reasoning, response

    # Case 2: Only </think> exists in output (because <think> was at end of prompt)
    if "</think>" in cleaned:
        parts = cleaned.split("</think>", 1)
        reasoning = parts[0].replace("<think>", "").strip()
        response = parts[1].strip()
        return reasoning, response

    # Case 3: Only <think> exists (incomplete reasoning)
    if "<think>" in cleaned:
        parts = cleaned.split("<think>", 1)
        reasoning = parts[1].strip()
        return reasoning, ""

    # Case 4: Pure numbered reasoning steps (e.g. 1. ... 2. ...)
    lines = cleaned.splitlines()
    if any(re.match(r"^\s*\d+\.", l) for l in lines):
        return cleaned, ""

    return None, cleaned
